DOCTORS_DATA = [
    {
        "email": "cardio.demo@sabiodoc.app",
        "password": "DemoDoctor123!",
        "display_name": "Dra. Valeria Rios",
        "professional_title": "Cardiologa clinica",
        "bio_short": "Cardiologa clinica enfocada en hipertension, palpitaciones y evaluacion preventiva.",
        "price_per_min_cents": 2200,
        "license_number": "COL-CARD-1001",
        "license_country": "Colombia",
        "country": "Colombia",
        "city": "Bogota",
        "timezone": "America/Bogota",
        "government_id": "CC-1002003001",
        "years_experience": 12,
        "specialty_slugs": ["cardiologia", "medicina-interna"],
        "availability_slots": [
            {"weekday": 0, "start": "09:00", "end": "12:00"},
            {"weekday": 2, "start": "14:00", "end": "18:00"},
            {"weekday": 4, "start": "09:00", "end": "12:00"}
        ],
        "presence_status": "online",
        "presence_message": "En linea - Disponible ahora",
        "rating_avg": 4.8,
        "rating_count": 124,
        "status": "approved",
    },
    {
        "email": "derma.demo@sabiodoc.app",
        "password": "DemoDoctor123!",
        "display_name": "Dr. Mateo Sosa",
        "professional_title": "Dermatologo",
        "bio_short": "Dermatologo con enfoque practico en acne, dermatitis y seguimiento de lesiones.",
        "price_per_min_cents": 1800,
        "license_number": "COL-DERM-2040",
        "license_country": "Colombia",
        "country": "Colombia",
        "city": "Medellin",
        "timezone": "America/Bogota",
        "government_id": "CC-1010101010",
        "years_experience": 9,
        "specialty_slugs": ["dermatologia"],
        "availability_slots": [
            {"weekday": 1, "start": "10:00", "end": "13:00"},
            {"weekday": 3, "start": "15:00", "end": "19:00"}
        ],
        "presence_status": "busy",
        "presence_message": "En linea - En consulta",
        "rating_avg": 4.6,
        "rating_count": 89,
        "status": "approved",
    },
    {
        "email": "neuro.demo@sabiodoc.app",
        "password": "DemoDoctor123!",
        "display_name": "Dra. Camila Ortega",
        "professional_title": "Neurologa",
        "bio_short": "Neurologa para cefalea, mareo, trastornos del sueno y sintomas neurologicos iniciales.",
        "price_per_min_cents": 2600,
        "license_number": "COL-NEU-3099",
        "license_country": "Colombia",
        "country": "Colombia",
        "city": "Cali",
        "timezone": "America/Bogota",
        "government_id": "CC-1098765432",
        "years_experience": 14,
        "specialty_slugs": ["neurologia"],
        "availability_slots": [
            {"weekday": 0, "start": "08:00", "end": "11:00"},
            {"weekday": 5, "start": "09:00", "end": "13:00"}
        ],
        "presence_status": "offline",
        "presence_message": "Desconectado",
        "rating_avg": 4.9,
        "rating_count": 203,
        "status": "approved",
    },
]
